export const CREATE_QUOTE_FETCHING = 'CREATE_QUOTE_FETCHING';
export const CREATE_QUOTE_SUCCESS = 'CREATE_QUOTE_SUCCESS';
export const CREATE_QUOTE_ERROR = 'CREATE_QUOTE_ERROR';
export const UPDATE_QUOTE_FETCHING = 'UPDATE_QUOTE_FETCHING';
export const UPDATE_QUOTE_SUCCESS = 'UPDATE_QUOTE_SUCCESS';
export const UPDATE_QUOTE_ERROR = 'UPDATE_QUOTE_ERROR';
